// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jqcayhxuuqfiudexdywu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpxY2F5aHh1dXFmaXVkZXhkeXd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNzQ3NTgsImV4cCI6MjA3Mjg1MDc1OH0.PLRQ68x2FjbuwIgGAfylaJG3izsr1aLW1u3pVIc-A7o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});